#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>

#include "search.h"
#include "evaluate.h"
#include "hash_tables.h"
#include "../movefinding/board.h"
#include "../movefinding/movefinder.h"

#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MIN(a, b) ((a) < (b) ? (a) : (b))

static ULL nodes_analysed = 0;
static int32_t best_eval = 0;
static int32_t prev_eval = 0;
static uint8_t searched_depth = 0;

static clock_t start_time = 0;
static clock_t global_max_time = 0;
static bool time_up = false;
static double time_spent = 0.0;

/*
 * Unified negamax.
 *
 * When return_best_move != NULL we are at the root:
 *   - Children are already generated by the caller (find_best_move).
 *     move_finder() must NOT be called again or num_children will corrupt.
 *   - TT is consulted for move ordering only; no alpha/beta pruning from TT
 *     (we want the true best move, not a hash-table shortcut).
 *   - Repetition check is skipped (root is already in the past-move list
 *     as the current game position; checking it would immediately draw).
 *   - best child is written to *return_best_move on success.
 *   - Children are NOT freed here; find_best_move owns that cleanup.
 *
 * When return_best_move == NULL we are at an interior node:
 *   - move_finder() is called here.
 *   - Full TT behaviour (lookup + store).
 *   - free_children_memory() is called before every return path.
 */
static int32_t negamax(Position_t *position, uint8_t depth,
                       int32_t alpha, int32_t beta,
                       Position_t *return_best_move);

int compare_positions_desc(const void *a, const void *b)
{
    const Position_t *pa = *(const Position_t **)a;
    const Position_t *pb = *(const Position_t **)b;
    if (pb->evaluation > pa->evaluation) return  1;
    if (pb->evaluation < pa->evaluation) return -1;
    return 0;
}

static inline void sort_children(Position_t *position)
{
    uint16_t n = position->num_children;
    if (n <= 1) { clear_grandchildren_count(position); return; }
    qsort(position->child_positions, n, sizeof(Position_t *), compare_positions_desc);
    clear_grandchildren_count(position);
}

static inline bool time_is_up(void)
{
    time_up = (clock() - start_time) >= global_max_time;
    return time_up;
}

int32_t find_best_move(Position_t *position,
                       Position_t *return_best_move,
                       uint8_t max_depth,
                       long long max_time)
{
    start_time = clock();
    global_max_time = max_time * CLOCKS_PER_SEC / 1000;
#if DEBUG
    nodes_analysed = 0;
#endif
    searched_depth = 1;
    best_eval = 0;
    prev_eval = 0;
    move_finder(position);

    /*
     * saved_best_move tracks the result of the last *fully completed* depth.
     * We only commit to it when a search finishes cleanly (not on timeout or
     * inside a re-search loop), so return_best_move is never left in a
     * partially-searched state.
     *
     * Initialised to *position as a safe fallback; the "no move found" check
     * at the end detects this via zobrist key comparison.
     */
    Position_t saved_best_move = *position;

    /* ------------------------------------------------------------------ */
    /* Full-window iterative deepening for the first few plies             */
    /* ------------------------------------------------------------------ */
    while (!time_is_up()
           && searched_depth < FULL_ASPIRATION_WINDOW_DEPTH
           && searched_depth <= max_depth)
    {
        sort_children(position);
        int32_t eval = negamax(position, searched_depth,
                               -INT32_MAX, INT32_MAX, return_best_move);
        if (eval == RAN_OUT_OF_TIME) { break; }
        saved_best_move = *return_best_move;   /* commit completed depth */
        best_eval = eval;
        prev_eval = eval;
        searched_depth++;
    }

    /* ------------------------------------------------------------------ */
    /* Aspiration window search                                            */
    /* ------------------------------------------------------------------ */
    while (!time_is_up() && searched_depth <= max_depth)
    {
        sort_children(position);

        int32_t alpha = prev_eval - ASPIRATION_WINDOW;
        int32_t beta  = prev_eval + ASPIRATION_WINDOW;
        int32_t eval;

        while (1) {
            eval = negamax(position, searched_depth, alpha, beta, return_best_move);

            if (eval == RAN_OUT_OF_TIME) { break; }

            if (eval <= alpha) {
                /* Fail-low: widen window downward, do NOT commit */
                alpha -= 5 * ASPIRATION_WINDOW;

            } else if (eval >= beta) {
                /* Fail-high: widen window upward, do NOT commit */
                beta += 5 * ASPIRATION_WINDOW;

            } else {
                /* Fully inside window — commit */
                best_eval = eval;
                saved_best_move = *return_best_move;
                break;
            }

            /* Window has grown too wide; fall back to full-width search */
            if (alpha < -12000 || beta > 12000) {
                eval = negamax(position, searched_depth,
                               -INT32_MAX, INT32_MAX, return_best_move);
                if (eval != RAN_OUT_OF_TIME) {
                    best_eval = eval;
                    saved_best_move = *return_best_move;
                }
                break;
            }

            /* Mate score detected — no point widening further */
            if (eval > CHECKMATE_VALUE - 1000 || eval < -CHECKMATE_VALUE + 1000) {
                best_eval = eval;
                prev_eval = eval;
                saved_best_move = *return_best_move;
                break;
            }
        }
        prev_eval = best_eval;
        searched_depth++;
    }

    /* Always restore the last cleanly-committed result */
    *return_best_move = saved_best_move;

    /*
     * If no move was ever committed (mate is inevitable from the root),
     * do a bare depth-1 search just to return a legal move.
     */
    if (position->zobrist_key == return_best_move->zobrist_key) {
        negamax(position, 1, -INT32_MAX, INT32_MAX, return_best_move);
        /* Small pause so the GUI can finish its current frame */
        struct timespec ts = {0, 50 * 1000000}; /* 50 ms */
        nanosleep(&ts, NULL);
    }

    free_children_memory(position);

    clock_t end_time = clock();
    time_spent = (double)(end_time - start_time) / CLOCKS_PER_SEC;
    return best_eval;
}

static int32_t negamax(Position_t *position, uint8_t depth,
                       int32_t alpha, int32_t beta,
                       Position_t *return_best_move)
{
    const bool is_root = (return_best_move != NULL);

    /* ------------------------------------------------------------------ */
    /* Base case                                                           */
    /* ------------------------------------------------------------------ */
    if (depth == 0) {
#if DEBUG
        nodes_analysed++;
#endif
        return evaluate_position(position);
    }

    /* ------------------------------------------------------------------ */
    /* Threefold-repetition draw (skip at root — root position is already  */
    /* in the past-move list; we don't want an instant draw evaluation)    */
    /* ------------------------------------------------------------------ */
    if (!is_root && is_threefold_repetition(position)) {
#if DEBUG
        nodes_analysed++;
#endif
        return 0;
    }

    /* ------------------------------------------------------------------ */
    /* Transposition table                                                 */
    /* ------------------------------------------------------------------ */
    const ULL key = position->zobrist_key;
    TranspositionEntry_t *entry = &transposition_table[key & TT_MASK];
    bool tt_move_found = false;
    int32_t orig_alpha = alpha;

    if (entry->zobrist_key == key) {
        tt_move_found = true;
        /*
         * At the root we use the TT only for move ordering.
         * Applying alpha/beta cutoffs here would suppress the best-move
         * output even when the TT score is stale from a narrower window.
         */
        if (!is_root && entry->search_depth >= depth) {
#if DEBUG
            nodes_analysed++;
#endif
            if (entry->node_type == EXACT) {
                return entry->position_evaluation;
            } else if (entry->node_type == LOWER_BOUND) {
                alpha = MAX(alpha, entry->position_evaluation);
            } else if (entry->node_type == UPPER_BOUND) {
                beta  = MIN(beta,  entry->position_evaluation);
            }
            if (alpha >= beta) {
                return entry->position_evaluation;
            }
        }
    }

    /* ------------------------------------------------------------------ */
    /* Move generation                                                     */
    /* Root children were already generated by find_best_move; calling    */
    /* move_finder again would double-append to num_children.             */
    /* ------------------------------------------------------------------ */
    if (!is_root) { move_finder(position); }

    /* ------------------------------------------------------------------ */
    /* Terminal node: no legal moves                                       */
    /* ------------------------------------------------------------------ */
    if (position->num_children == 0) {
#if DEBUG
        nodes_analysed++;
#endif
        /*
         * We already know num_children == 0; is_check is sufficient.
         */
        if (!is_root) { free_children_memory(position); }
        return is_check(position, position->white_to_move)
                   ? -CHECKMATE_VALUE + (searched_depth - depth)
                   : 0; /* stalemate */
    }

    /* ------------------------------------------------------------------ */
    /* TT move ordering: move the TT best-move to the front               */
    /* ------------------------------------------------------------------ */
    if (tt_move_found) {
        for (uint16_t i = 0; i < position->num_children; i++) {
            if (position->child_positions[i]->zobrist_key
                    == entry->best_move_zobrist_key) {
                if (i != 0) {
                    Position_t *tmp            = position->child_positions[0];
                    position->child_positions[0] = position->child_positions[i];
                    position->child_positions[i] = tmp;
                }
                break;
            }
        }
    }

    /* ------------------------------------------------------------------ */
    /* Main negamax loop                                                   */
    /* ------------------------------------------------------------------ */
    int32_t value = -INT32_MAX + 1;
    int best_child_idx = -1;

    for (uint16_t i = 0; i < position->num_children; i++)
    {
        /* Check clock periodically — every child is cheap enough */
        if (time_is_up()) {
            if (!is_root) { free_children_memory(position); }
            return RAN_OUT_OF_TIME;
        }

        Position_t *child = position->child_positions[i];

        insert_past_move_entry(child);
        int32_t score = negamax(child, depth - 1, -beta, -alpha, NULL);
        clear_past_move_entry(child);

        /*
         * CRITICAL: check for timeout BEFORE negating.
         * RAN_OUT_OF_TIME == -9997799; negating it gives +9997799 which
         * looks like a brilliant move and would corrupt the result.
         */
        if (score == RAN_OUT_OF_TIME) {
            if (!is_root) { free_children_memory(position); }
            return RAN_OUT_OF_TIME;
        }
        score = -score;

        /* Store score on child for move-ordering in the next iteration */
        child->evaluation = score;

        if (score > value) {
            value = score;
            best_child_idx = i;
        }
        if (value > alpha) {
            alpha = value;
            if (alpha >= beta) { break; /* Beta cutoff */ }
        }
    }

    /* ------------------------------------------------------------------ */
    /* Root return: write best move and skip TT store                     */
    /* ------------------------------------------------------------------ */
    if (is_root) {
        clear_grandchildren_count(position);
        if (best_child_idx >= 0) {
            *return_best_move = *position->child_positions[best_child_idx];
        } else {
            *return_best_move = *position; /* safety fallback */
        }
        return value;
    }

    /* ------------------------------------------------------------------ */
    /* Transposition table store                                           */
    /* ------------------------------------------------------------------ */
    if (best_child_idx >= 0) {
        entry->zobrist_key = key;
        entry->position_evaluation = value;
        entry->half_move_count = position->half_move_count;
        entry->search_depth = depth;

        if (value <= orig_alpha) {
            entry->node_type = UPPER_BOUND;   /* fail-low  */
        } else if (value >= beta) {
            entry->node_type = LOWER_BOUND;   /* fail-high */
        } else {
            entry->node_type = EXACT;
        }
        entry->best_move_zobrist_key =
            position->child_positions[best_child_idx]->zobrist_key;
    }

    free_children_memory(position);
    return value;
}

void print_stats(void)
{
    printf("Depth: %u | Time: %.4fs | Positions: %lu | Nodes: %llu | Eval: %d\n",
           searched_depth - 1, time_spent, get_num_new_positions(),
           nodes_analysed, best_eval);
}

