#include <stdint.h>
#include <stdlib.h>
#include <sys/types.h>
#include <stdio.h>
#include <time.h>
#include <string.h>

#include "search.h"
#include "evaluate.h"
#include "hash_tables.h"
#include "../movefinding/board.h"
#include "../movefinding/movefinder.h"

#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MIN(a, b) ((a) < (b) ? (a) : (b))

typedef struct {
    uint8_t from_sq;
    uint8_t to_sq;
} Killer_t;

static Killer_t killer_moves[MAX_SEARCH_DEPTH][2];

static int32_t best_eval = 0;
static int32_t prev_eval = 0;
static uint8_t searched_depth = 0;
static uint8_t completed_depth = 0;

static clock_t start_time = 0;
static clock_t global_max_time = 0;
static bool time_up = false;

static ULL nodes_analysed = 0;
static uint32_t aspiration_attempts = 0;
static uint32_t aspiration_failures = 0;
static uint32_t beta_count = 0;
static uint32_t beta_first_move_count = 0;
static uint64_t total_moves_before_cutoff = 0;
static ULL interior_nodes = 0;


/*
 * Unified negamax.
 *
 * When return_best_move != NULL we are at the root:
 *   - Children are already generated by the caller (find_best_move).
 *     move_finder() must NOT be called again or num_children will corrupt.
 *   - TT is consulted for move ordering only; no alpha/beta pruning from TT
 *     (we want the true best move, not a hash-table shortcut).
 *   - Repetition check is skipped (root is already in the past-move list
 *     as the current game position; checking it would immediately draw).
 *   - best child is written to *return_best_move on success.
 *   - Children are NOT freed here; find_best_move owns that cleanup.
 *
 * When return_best_move == NULL we are at an interior node:
 *   - move_finder() is called here.
 *   - Full TT behaviour (lookup + store).
 *   - free_children_memory() is called before every return path.
 */
static int32_t negamax(Position_t *position, uint8_t depth,
                       int32_t alpha, int32_t beta,
                       Position_t *return_best_move);

static int32_t quiescence(Position_t *position, int32_t alpha, int32_t beta,
                          uint8_t qdepth);

static inline int compare_positions_desc(const void *a, const void *b)
{
    const Position_t *pa = *(const Position_t **)a;
    const Position_t *pb = *(const Position_t **)b;
    if (pb->evaluation > pa->evaluation) return  1;
    if (pb->evaluation < pa->evaluation) return -1;
    return 0;
}

static inline void sort_children(Position_t *position)
{
    uint16_t n = position->num_children;
    if (n <= 1) { clear_grandchildren_count(position); return; }
    qsort(position->child_positions, n, sizeof(Position_t *), compare_positions_desc);
    clear_grandchildren_count(position);
}

static inline bool time_is_up(void)
{
    if ((nodes_analysed & 4095) != 0) { return false; }  // check every 4096 nodes
    time_up = (clock() - start_time) >= global_max_time;
    return time_up;
}


int32_t find_best_move(Position_t *position,
                       Position_t *return_best_move,
                       uint8_t max_depth,
                       long long max_time)
{
    start_time = clock();
    global_max_time = max_time * CLOCKS_PER_SEC / 1000;
    best_eval = 0;
    prev_eval = 0;
    completed_depth = 0;
    searched_depth = 1;

    nodes_analysed = 0;
    interior_nodes = 0;
    aspiration_attempts = 0;
    aspiration_failures  = 0;
    beta_count = 0;
    beta_first_move_count = 0;
    total_moves_before_cutoff = 0;

    memset(killer_moves, 0, sizeof(killer_moves));

    move_finder(position);

    Position_t saved_best_move = *position;

    /* ------------------------------------------------------------------ */
    /* Full-window iterative deepening for the first few plies             */
    /* ------------------------------------------------------------------ */
    while (!time_is_up()
           && searched_depth < FULL_ASPIRATION_WINDOW_DEPTH
           && searched_depth <= max_depth)
    {
        sort_children(position);
        int32_t eval = negamax(position, searched_depth,
                               -INT32_MAX, INT32_MAX, return_best_move);
        if (eval == RAN_OUT_OF_TIME) { break; }
        saved_best_move = *return_best_move;
        best_eval = eval;
        prev_eval = eval;
        completed_depth = searched_depth;   /* this depth finished cleanly */
        searched_depth++;
    }

    /* ------------------------------------------------------------------ */
    /* Aspiration window search                                            */
    /* ------------------------------------------------------------------ */
    while (!time_is_up() && searched_depth <= max_depth)
    {
        sort_children(position);

        int32_t alpha = prev_eval - ASPIRATION_WINDOW;
        int32_t beta  = prev_eval + ASPIRATION_WINDOW;
        int32_t eval;
        bool depth_failed = false;   /* did this depth need a retry? */
        aspiration_attempts++;       /* one attempt per depth */

        while (1) {
            eval = negamax(position, searched_depth, alpha, beta, return_best_move);

            if (eval == RAN_OUT_OF_TIME) { break; } /* check timeout first */

            if (eval <= alpha) {
                depth_failed = true;
                alpha -= 5 * ASPIRATION_WINDOW;

            } else if (eval >= beta) {
                depth_failed = true;
                beta += 5 * ASPIRATION_WINDOW;

            } else {
                // Fully inside window — commit
                best_eval = eval;
                saved_best_move = *return_best_move;
                completed_depth = searched_depth;
                break;
            }

            /* fall back to full-width if window is huge,
             * or if we saw a positive mate (fail-high) */
            if (alpha < -12000 || beta > 12000 ||
                (eval > CHECKMATE_VALUE - 1000 && eval >= beta)) {
                eval = negamax(position, searched_depth,
                               -INT32_MAX, INT32_MAX, return_best_move);
                if (eval != RAN_OUT_OF_TIME) {
                    best_eval = eval;
                    saved_best_move = *return_best_move;
                    prev_eval = eval;
                    completed_depth = searched_depth;
                }
                break;
            }

            // Mate score detected — no point widening further
            if (eval > CHECKMATE_VALUE - 1000 || eval < -CHECKMATE_VALUE + 1000) {
                best_eval = eval;
                prev_eval = eval;
                saved_best_move = *return_best_move;
                completed_depth = searched_depth;
                break;
            }
        }

        if (depth_failed) { aspiration_failures++; }  // one failure per depth

        prev_eval = best_eval;
        searched_depth++;
    }

    *return_best_move = saved_best_move;

    if (position->zobrist_key == return_best_move->zobrist_key) {
        negamax(position, 1, -INT32_MAX, INT32_MAX, return_best_move);
        struct timespec ts = {0, 50 * 1000000};
        nanosleep(&ts, NULL);
    }

    free_children_memory(position);

    return best_eval;
}

static int32_t negamax(Position_t *position, uint8_t depth,
                       int32_t alpha, int32_t beta,
                       Position_t *return_best_move)
{
    const bool is_root = (return_best_move != NULL);

    if (depth > 0 && !is_root) { interior_nodes++; }

    /* ------------------------------------------------------------------ */
    /* Base case — hand off to quiescence search instead of evaluating    */
    /* statically, so captures beyond the horizon are not missed.         */
    /* ------------------------------------------------------------------ */
    if (depth == 0) {
        return quiescence(position, alpha, beta, MAX_QUIESCENCE_DEPTH);
    }

    // ------------------------------------------------------------------
    // Threefold-repetition draw (skip at root — root position is already
    // in the past-move list; we don't want an instant draw evaluation)
    // ------------------------------------------------------------------
    if (!is_root && is_repetition(position, 2)) {
        nodes_analysed++;
        return 0;
    }

    // -------------------------------------------------------------
    // Transposition table
    // ---------------------------------------------------------------
    const ULL key = position->zobrist_key;
    TranspositionEntry_t *entry = &transposition_table[key & TT_MASK];
    bool tt_move_found = false;
    int32_t orig_alpha = alpha;

    ULL entry_key = entry->zobrist_key;
    if (__builtin_expect(entry_key == key, 0)) {
        tt_move_found = true;
        /*
         * At the root we use the TT only for move ordering.
         * Applying alpha/beta cutoffs here would suppress the best-move
         * output even when the TT score is stale from a narrower window.
         */
        if (__builtin_expect(!is_root, 1)) {
            int32_t entry_depth = entry->search_depth;
            if (entry_depth >= depth) {
                nodes_analysed++;
                int32_t entry_eval = entry->position_evaluation;
                switch (entry->node_type) {
                    case EXACT:
                        return entry_eval;
                    case LOWER_BOUND:
                        if (entry_eval > alpha) alpha = entry_eval;
                        break;
                    case UPPER_BOUND:
                        if (entry_eval < beta) beta = entry_eval;
                        break;
                    default:
                        break;
                }
                if (alpha >= beta) {
                    beta_count++;
                    total_moves_before_cutoff++;

                    return entry_eval;
                }
            }
        }
    }

    // ------------------------------------------------------------------
    // Move generation
    // ------------------------------------------------------------------
    if (__builtin_expect(!is_root, 1)) { move_finder(position); }

    const uint16_t pos_num_chldrn = position->num_children;
    // ------------------------------------------------------------------
    // Terminal node: no legal moves
    // ------------------------------------------------------------------
    if (pos_num_chldrn == 0) {
        nodes_analysed++;
        // We already know num_children == 0; is_check is sufficient.
        if (__builtin_expect(!is_root, 1)) { free_children_memory(position); }

        return is_check(position, position->white_to_move)
                   ? -CHECKMATE_VALUE + (searched_depth - depth) : 0; // stalemate
    }

    // ------------------------------------------------------------------
    // TT move ordering: move the TT best-move to the front
    // ------------------------------------------------------------------
    if (tt_move_found) {
        for (uint16_t i = 0; i < pos_num_chldrn; i++) {
            if (position->child_positions[i]->zobrist_key
                    == entry->best_move_zobrist_key) {
                if (i != 0) {
                    Position_t *tmp            = position->child_positions[0];
                    position->child_positions[0] = position->child_positions[i];
                    position->child_positions[i] = tmp;
                }
                break;
            }
        }
    }

    uint16_t sort_start = (tt_move_found) ? 1 : 0;

    // ------------------------------------------------------------------
    // Killer move ordering:
    // ------------------------------------------------------------------
    for (uint16_t i = sort_start; i < pos_num_chldrn; i++) {
        Position_t* child = position->child_positions[i];
        if (child->evaluation > KILLER_EVALUATION) { continue; } // skip captures
        if (child->from_sq == killer_moves[depth][0].from_sq &&
            child->to_sq == killer_moves[depth][0].to_sq) {
            child->evaluation = KILLER_EVALUATION;
        } else if (child->from_sq == killer_moves[depth][1].from_sq &&
            child->to_sq == killer_moves[depth][1].to_sq) {
            child->evaluation = KILLER_EVALUATION - 10;
        }
    }

    // ------------------------------------------------------------------
    // Main negamax loop
    // ------------------------------------------------------------------
    int32_t value = -INT32_MAX + 1;
    int best_child_idx = -1;


    for (uint16_t i = 0; i < pos_num_chldrn; i++)
    {
        // Check clock periodically — every child is cheap enough
        if (time_is_up()) {
            if (__builtin_expect(!is_root, 1)) { free_children_memory(position); }
            return RAN_OUT_OF_TIME;
        }

        if (i >= sort_start) {
            uint16_t best = i;

            for (uint16_t j = i + 1; j < pos_num_chldrn; j++) {
                if (position->child_positions[j]->evaluation >
                    position->child_positions[best]->evaluation) {
                    best = j;
                }
            }
            if (best != i) {
                Position_t *tmp = position->child_positions[i];
                position->child_positions[i] = position->child_positions[best];
                position->child_positions[best] = tmp;
            }
        }

        Position_t *child = position->child_positions[i];

        insert_past_move_entry(child);
        int32_t score = negamax(child, depth - 1, -beta, -alpha, NULL);
        clear_past_move_entry();

        // check for timeout BEFORE negating. negating it gives +9997799 which
        // looks like a brilliant move and would corrupt the result.
        if (score == RAN_OUT_OF_TIME) {
            if (!is_root) { free_children_memory(position); }
            return RAN_OUT_OF_TIME;
        }
        score = -score;

        // Store score on child for move-ordering in the next iteration
        child->evaluation = score;

        if (score > value) {
            value = score;
            best_child_idx = i;
        }
        if (value > alpha) {
            alpha = value;
            if (alpha >= beta) {
                beta_count++;
                total_moves_before_cutoff += (i + 1);  // i is 0-indexed
                if (i == 0) { beta_first_move_count++; }

                // Killer move herusitc - if not a capture move and a cutoff move
                // then store the move to try at the next sibling node
                bool is_capture = (child->piece_value_diff != position->piece_value_diff);
                if (!is_capture) {
                    killer_moves[depth][1] = killer_moves[depth][0];
                    killer_moves[depth][0] = (Killer_t){child->from_sq, child->to_sq};
                }

                break; /* Beta cutoff */
            }
        }
    }

    // ------------------------------------------------------------------
    // Root return: write best move and skip TT store
    // ------------------------------------------------------------------
    if (is_root) {
        clear_grandchildren_count(position);
        if (best_child_idx >= 0) {
            *return_best_move = *position->child_positions[best_child_idx];
        } else {
            *return_best_move = *position; /* safety fallback */
        }
        return value;
    }

    // ------------------------------------------------------------------
    // Transposition table store
    // ------------------------------------------------------------------
    if (best_child_idx >= 0) {
        entry->zobrist_key = key;
        entry->position_evaluation = value;
        entry->half_move_count = position->half_move_count;
        entry->search_depth = depth;

        if (value <= orig_alpha) {
            entry->node_type = UPPER_BOUND;   // fail-low
        } else if (value >= beta) {
            entry->node_type = LOWER_BOUND;   // fail-high
        } else {
            entry->node_type = EXACT;
        }
        entry->best_move_zobrist_key =
            position->child_positions[best_child_idx]->zobrist_key;
    }

    free_children_memory(position);
    return value;
}

static int32_t quiescence(Position_t *position, int32_t alpha, int32_t beta,
                          uint8_t qdepth)
{
    nodes_analysed++;
    bool in_check = is_check(position, position->white_to_move);

    if (!in_check) {
        int32_t stand_pat = evaluate_position(position);
        if (stand_pat >= beta) { return stand_pat;} // beta cut
        if (stand_pat > alpha) { alpha = stand_pat;} // raise minimum alpha
    }

    // depth limit 
    // Not in check: stand-pat is a valid return.
    // In checkmate: return mate score
    // In check: generate escape moves
    if (qdepth == 0) {
        if (!in_check) { return alpha; }
        // else WE ARE IN CHECK:
        move_finder(position);
        uint16_t num_children = position->num_children;
        if (num_children == 0) { // must be checkmate if we can't move
            // return the loss score
            free_children_memory(position);
            return -CHECKMATE_VALUE + searched_depth + MAX_QUIESCENCE_DEPTH;
        }
        // at this point we are not in checkmate but need to move out of check:
        for (uint16_t i = 0; i < num_children; i++) {
            int32_t evaluation = -evaluate_position(position->child_positions[i]);
            if (evaluation >= beta) { free_children_memory(position); return evaluation;}
            if (evaluation > alpha) { alpha = evaluation; } // raise minimum alpha!
        }

        // return best move out of check score:
        free_children_memory(position);
        return alpha;

    }

    move_finder(position);
    uint16_t num_children = position->num_children;

    // terminal node - then either checkmate or stalemate if no children!!
    if (num_children == 0) {
        free_children_memory(position);
        if (in_check) { //checkmate
            return -CHECKMATE_VALUE + searched_depth + (MAX_QUIESCENCE_DEPTH - qdepth);
        } else { return 0; } // stalemate
    }

    // at this point we are not at depth limit, nor are we at a terminal node
    // so now we can do what we need to - do a capture search branch

    int32_t parent_diff = position->piece_value_diff;
    for (uint16_t i = 0; i < num_children; i++) {

        // lazy sort - find best capture from i onwards and swap it here
        uint16_t best = i;
        for (uint16_t j = i + 1; j < position->num_children; j++) {
            if (position->child_positions[j]->evaluation >
                position->child_positions[best]->evaluation) {
                best = j;
            }
        }
        if (best != i) {
            Position_t *tmp = position->child_positions[i];
            position->child_positions[i] = position->child_positions[best];
            position->child_positions[best] = tmp;
        }

        Position_t* child = position->child_positions[i];

        // skip children that don't have captures:
        if (!in_check && child->piece_value_diff == parent_diff) { continue; }

        // otherwise compute children recursively:
        insert_past_move_entry(child);
        int32_t score = -quiescence(child, -beta, -alpha, qdepth - 1);
        clear_past_move_entry();

        // alpha-beta cutoff:
        if (score > alpha) {
            alpha = score; // update alpha to meet minimum expected value
            if (alpha >= beta) {
                free_children_memory(position);
                return alpha; // beta cut-off
            }
        }
    }

    // normal return path
    free_children_memory(position);
    return alpha;
}

void print_stats(void)
{
    float beta_rate = interior_nodes > 0
                    ? (float)beta_count * 100.0f / (float)interior_nodes
                    : 0.0f;
    float first_move_rate = beta_count > 0
                           ? (float)beta_first_move_count * 100.0f / (float)beta_count
                           : 0.0f;
    float avg = beta_count > 0 ? (float)total_moves_before_cutoff / beta_count : 0.0f;
    printf("Depth: %u | Nodes: %llu | Eval: %d | "
           "A. fail rate: %.1f%% | "
           "Beta: %.1f%% | 1st move: %.1f%% | "
           "Avg bef. cut: %.2f\n",
           completed_depth, nodes_analysed, best_eval,
           (float)aspiration_failures * 100.0 / aspiration_attempts,
           beta_rate, first_move_rate, avg);
}

